name: health_calculators
description: "For body mass index and basal metabolic rate calculations easily and accurately, Used in CalorieKit"
version: 0.1.2
repository: https://github.com/caloriekit/health_calculators_flutter

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
