name: health_calculators
description: "Calculate BMI and BMR"
version: 0.1.0
repository: https://github.com/caloriekit/health_calculators_flutter.git

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: